# Generated by Django 5.0.6 on 2024-10-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(max_length=50, verbose_name='Project Type')),
                ('pname', models.CharField(max_length=200, verbose_name='Project Name')),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
