# Generated by Django 5.1.4 on 2024-12-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimage', models.ImageField(upload_to='project_images')),
                ('pname', models.CharField(max_length=30, verbose_name='Project Name')),
                ('desc', models.CharField(max_length=100, verbose_name='Project Description')),
            ],
        ),
    ]
