# Generated by Django 5.0.6 on 2024-12-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='sdesc',
            field=models.CharField(max_length=100, verbose_name='Description of the Service'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sname',
            field=models.CharField(max_length=30, verbose_name='Name of the Service'),
        ),
    ]
