# Generated by Django 5.1.4 on 2025-01-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_projects_db_projects_framework_projects_ide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='db',
        ),
        migrations.AddField(
            model_name='projects',
            name='database',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Database Used'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='framework',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Framework Used'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='ide',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IDE Used'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Language Used'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='userinterface',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User Interface'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='webbrowser',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Web Browser'),
        ),
    ]
