# Generated by Django 5.1.4 on 2025-01-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_projects_db_projects_database_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='database',
            field=models.CharField(max_length=50, null=True, verbose_name='Database Used'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='framework',
            field=models.CharField(max_length=50, null=True, verbose_name='Framework Used'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='ide',
            field=models.CharField(max_length=50, null=True, verbose_name='IDE Used'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='language',
            field=models.CharField(max_length=50, null=True, verbose_name='Language Used'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='userinterface',
            field=models.CharField(max_length=50, null=True, verbose_name='User Interface'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='webbrowser',
            field=models.CharField(max_length=50, null=True, verbose_name='Web Browser'),
        ),
    ]
