# Generated by Django 5.1.4 on 2025-01-05 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_projects_database_alter_projects_framework_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='pimage',
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.projects')),
            ],
        ),
    ]
