# Generated by Django 5.1.4 on 2025-01-14 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projects', verbose_name='Project/Services ID'),
        ),
    ]
