# Generated by Django 5.1.4 on 2025-01-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_cart_services_alter_cart_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
