# Generated by Django 5.0.6 on 2024-12-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_services_sdesc_alter_services_sname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='sdesc',
            field=models.CharField(max_length=150, verbose_name='Description of the Service'),
        ),
    ]
