# Generated by Django 5.0.6 on 2024-12-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_services_sdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Team Member Name')),
                ('designation', models.CharField(max_length=50, verbose_name='Designation')),
                ('image', models.ImageField(upload_to='team_member')),
            ],
        ),
    ]
