# Generated by Django 5.1.4 on 2025-01-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_projects_pimage_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='pimage',
            field=models.ImageField(null=True, upload_to='project_images'),
        ),
    ]
