# Generated by Django 5.1.4 on 2025-01-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_servicesimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='pfile',
            field=models.FileField(blank=True, null=True, upload_to='project_files'),
        ),
    ]
