# Generated by Django 5.1.4 on 2025-01-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_projects_pfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='sfile',
            field=models.FileField(blank=True, null=True, upload_to='service_files'),
        ),
    ]
