# Generated by Django 5.1.4 on 2025-01-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_services_sfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='ptype',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Project type'),
        ),
    ]
