# Generated by Django 5.1.4 on 2025-01-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_money'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Money',
        ),
    ]
