# Generated by Django 5.1.4 on 2025-01-22 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_money_service_id_alter_money_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.services'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.projects'),
        ),
    ]
