# Generated by Django 5.1.4 on 2025-01-23 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
